var S = require('./engine.js');
var pass = 0, fail = 0;
function t(name, got, want) {
  var ok = JSON.stringify(got) === JSON.stringify(want);
  if (ok) pass++; else { fail++; console.log('FAIL ' + name + ': got ' + JSON.stringify(got) + ' want ' + JSON.stringify(want)); }
}
t('pr 9gpm 600sqft', S.precipRate(9, 600), 1.44);
t('pr 6gpm 600sqft', S.precipRate(6, 600), 0.96);
t('pr zero area safe', S.precipRate(9, 0), 0);
t('velocity 9gpm 3/4', S.pipeVelocity(9, '3/4 in'), 5.41);
t('velocity 9gpm 1in', S.pipeVelocity(9, '1 in'), 3.34);
t('velocity unknown pipe', S.pipeVelocity(9, '2 in'), null);
t('heads per zone sprays', S.headsPerZone(10, 1.5), 6);
t('heads per zone rotors', S.headsPerZone(10, 3), 3);
t('heads per zone never zero', S.headsPerZone(1, 5), 1);
t('zones 8 heads 6 per', S.zoneCount(8, 6), 2);
t('zones exact fit', S.zoneCount(6, 3), 2);
t('zones one enough', S.zoneCount(3, 3), 1);
t('weekly minutes 1in at 0.96', S.weeklyMinutes(1, 0.96), 62.5);
t('weekly minutes zero pr', S.weeklyMinutes(1, 0), 0);
t('max cycle loam 0.96', S.maxCycleMinutes('loam', 0.96), 25);
t('max cycle clay 1.44', S.maxCycleMinutes('clay', 1.44), 6.25);
t('max cycle sand 0.96', S.maxCycleMinutes('sand', 0.96), 50);
t('cycle plan fits', S.cyclePlan(20.83, 25, 'loam'), { cycles: 1, runMin: 20.83, soakMin: 0 });
t('cycle plan splits', S.cyclePlan(30, 6.25, 'clay'), { cycles: 5, runMin: 6, soakMin: 60 });
t('cycle plan loam soak 30', S.cyclePlan(60, 25, 'loam'), { cycles: 3, runMin: 20, soakMin: 30 });
t('fmt 83', S.fmtMin(83), '83 min');
t('fmt 125', S.fmtMin(125), '2h 05m');
t('fmt 400', S.fmtMin(400), '6h 40m');
var a = S.compute({ supplyGpm: 10, psi: 50, headType: 'spray', headCount: 8, areaSqft: 1200, soil: 'loam', pipeSize: '3/4 in', needInPerWeek: 1 });
t('spray perZone', a.perZone, 6);
t('spray zones', a.zones, 2);
t('spray heads in zone', a.headsInZone, 4);
t('spray zone gpm', a.zoneGpm, 6);
t('spray pr', a.pr, 0.96);
t('spray session', a.sessionMin, 20.83);
t('spray one cycle', a.plan.cycles, 1);
t('spray velocity ok', a.velocity, 3.61);
t('spray zones warn', a.checks.some(function (c) { return c.level === 'warn' && c.text.indexOf('4 heads each') > -1; }), true);
var b = S.compute({ supplyGpm: 12, psi: 50, headType: 'rotor', headCount: 6, areaSqft: 5000, soil: 'clay', pipeSize: '1 in', needInPerWeek: 1 });
t('rotor zones', b.zones, 2);
t('rotor pr slow', b.pr, 0.35);
t('rotor weekly', b.weeklyMin, 171.43);
t('rotor clay split', b.plan, { cycles: 3, runMin: 19.05, soakMin: 60 });
t('rotor slow warn', b.checks.some(function (c) { return c.level === 'warn' && c.text.indexOf('feels long') > -1; }), true);
var c = S.compute({ supplyGpm: 10, psi: 25, headType: 'drip', headCount: 40, areaSqft: 200, soil: 'loam', pipeSize: '3/4 in', needInPerWeek: 1 });
t('drip one zone', c.zones, 1);
t('drip pr', c.pr, 0.15);
t('drip weekly long', c.weeklyMin, 400);
t('drip no runoff', c.checks.some(function (c) { return c.level === 'good' && c.text.indexOf('no runoff') > -1; }), true);
var d = S.compute({ supplyGpm: 10, psi: 20, headType: 'spray', headCount: 4, areaSqft: 500, soil: 'loam', pipeSize: '3/4 in', needInPerWeek: 1 });
t('low psi bad', d.checks.some(function (x) { return x.level === 'bad' && x.text.indexOf('drool') > -1; }), true);
var e = S.compute({ supplyGpm: 15, psi: 55, headType: 'spray', headCount: 8, areaSqft: 1200, soil: 'sand', pipeSize: '3/4 in', needInPerWeek: 1 });
t('velocity bad', e.checks.some(function (x) { return x.level === 'bad' && x.text.indexOf('1 in pipe drops it') > -1; }), true);
t('rejects zero supply', S.compute({ supplyGpm: 0, headCount: 4, areaSqft: 100 }).error.length > 0, true);
console.log(pass + '/' + (pass + fail) + ' tests passed');
process.exit(fail ? 1 : 0);
